#include "moves.hpp"

std::string_view to_string(Move const move){
    switch (move) {
		case Move::Pass: return "Pass";
		case Move::Switch0: return "Switch0";
		case Move::Switch1: return "Switch1";
		case Move::Switch2: return "Switch2";
		case Move::Switch3: return "Switch3";
		case Move::Switch4: return "Switch4";
		case Move::Switch5: return "Switch5";
		case Move::Hit_Self: return "Hit self in confusion";

		case Move::Pound: return "Pound";
		case Move::Karate_Chop: return "Karate Chop";
		case Move::Double_Slap: return "Double Slap";
		case Move::Comet_Punch: return "Comet Punch";
		case Move::Mega_Punch: return "Mega Punch";
		case Move::Pay_Day: return "Pay Day";
		case Move::Fire_Punch: return "Fire Punch";
		case Move::Ice_Punch: return "Ice Punch";
		case Move::Thunder_Punch: return "Thunder Punch";
		case Move::Scratch: return "Scratch";
		case Move::Vice_Grip: return "Vice Grip";
		case Move::Guillotine: return "Guillotine";
		case Move::Razor_Wind: return "Razor Wind";
		case Move::Swords_Dance: return "Swords Dance";
		case Move::Cut: return "Cut";
		case Move::Gust: return "Gust";
		case Move::Wing_Attack: return "Wing Attack";
		case Move::Whirlwind: return "Whirlwind";
		case Move::Fly: return "Fly";
		case Move::Bind: return "Bind";
		case Move::Slam: return "Slam";
		case Move::Vine_Whip: return "Vine Whip";
		case Move::Stomp: return "Stomp";
		case Move::Double_Kick: return "Double Kick";
		case Move::Mega_Kick: return "Mega Kick";
		case Move::Jump_Kick: return "Jump Kick";
		case Move::Rolling_Kick: return "Rolling Kick";
		case Move::Sand_Attack: return "Sand Attack";
		case Move::Headbutt: return "Headbutt";
		case Move::Horn_Attack: return "Horn Attack";
		case Move::Fury_Attack: return "Fury Attack";
		case Move::Horn_Drill: return "Horn Drill";
		case Move::Tackle: return "Tackle";
		case Move::Body_Slam: return "Body Slam";
		case Move::Wrap: return "Wrap";
		case Move::Take_Down: return "Take Down";
		case Move::Thrash: return "Thrash";
		case Move::Double_Edge: return "Double-Edge";
		case Move::Tail_Whip: return "Tail Whip";
		case Move::Poison_Sting: return "Poison Sting";
		case Move::Twineedle: return "Twineedle";
		case Move::Pin_Missile: return "Pin Missile";
		case Move::Leer: return "Leer";
		case Move::Bite: return "Bite";
		case Move::Growl: return "Growl";
		case Move::Roar: return "Roar";
		case Move::Sing: return "Sing";
		case Move::Supersonic: return "Supersonic";
		case Move::Sonic_Boom: return "Sonic Boom";
		case Move::Disable: return "Disable";
		case Move::Acid: return "Acid";
		case Move::Ember: return "Ember";
		case Move::Flamethrower: return "Flamethrower";
		case Move::Mist: return "Mist";
		case Move::Water_Gun: return "Water Gun";
		case Move::Hydro_Pump: return "Hydro Pump";
		case Move::Surf: return "Surf";
		case Move::Ice_Beam: return "Ice Beam";
		case Move::Blizzard: return "Blizzard";
		case Move::Psybeam: return "Psybeam";
		case Move::Bubble_Beam: return "Bubble Beam";
		case Move::Aurora_Beam: return "Aurora Beam";
		case Move::Hyper_Beam: return "Hyper Beam";
		case Move::Peck: return "Peck";
		case Move::Drill_Peck: return "Drill Peck";
		case Move::Submission: return "Submission";
		case Move::Low_Kick: return "Low Kick";
		case Move::Counter: return "Counter";
		case Move::Seismic_Toss: return "Seismic Toss";
		case Move::Strength: return "Strength";
		case Move::Absorb: return "Absorb";
		case Move::Mega_Drain: return "Mega Drain";
		case Move::Leech_Seed: return "Leech Seed";
		case Move::Growth: return "Growth";
		case Move::Razor_Leaf: return "Razor Leaf";
		case Move::Solar_Beam: return "Solar Beam";
		case Move::Poison_Powder: return "Poison Powder";
		case Move::Stun_Spore: return "Stun Spore";
		case Move::Sleep_Powder: return "Sleep Powder";
		case Move::Petal_Dance: return "Petal Dance";
		case Move::String_Shot: return "String Shot";
		case Move::Dragon_Rage: return "Dragon Rage";
		case Move::Fire_Spin: return "Fire Spin";
		case Move::Thunder_Shock: return "Thunder Shock";
		case Move::Thunderbolt: return "Thunderbolt";
		case Move::Thunder_Wave: return "Thunder Wave";
		case Move::Thunder: return "Thunder";
		case Move::Rock_Throw: return "Rock Throw";
		case Move::Earthquake: return "Earthquake";
		case Move::Fissure: return "Fissure";
		case Move::Dig: return "Dig";
		case Move::Toxic: return "Toxic";
		case Move::Confusion: return "Confusion";
		case Move::Psychic: return "Psychic";
		case Move::Hypnosis: return "Hypnosis";
		case Move::Meditate: return "Meditate";
		case Move::Agility: return "Agility";
		case Move::Quick_Attack: return "Quick Attack";
		case Move::Rage: return "Rage";
		case Move::Teleport: return "Teleport";
		case Move::Night_Shade: return "Night Shade";
		case Move::Mimic: return "Mimic";
		case Move::Screech: return "Screech";
		case Move::Double_Team: return "Double Team";
		case Move::Recover: return "Recover";
		case Move::Harden: return "Harden";
		case Move::Minimize: return "Minimize";
		case Move::Smokescreen: return "Smokescreen";
		case Move::Confuse_Ray: return "Confuse Ray";
		case Move::Withdraw: return "Withdraw";
		case Move::Defense_Curl: return "Defense Curl";
		case Move::Barrier: return "Barrier";
		case Move::Light_Screen: return "Light Screen";
		case Move::Haze: return "Haze";
		case Move::Reflect: return "Reflect";
		case Move::Focus_Energy: return "Focus Energy";
		case Move::Bide: return "Bide";
		case Move::Metronome: return "Metronome";
		case Move::Mirror_Move: return "Mirror Move";
		case Move::Self_Destruct: return "Self-Destruct";
		case Move::Egg_Bomb: return "Egg Bomb";
		case Move::Lick: return "Lick";
		case Move::Smog: return "Smog";
		case Move::Sludge: return "Sludge";
		case Move::Bone_Club: return "Bone Club";
		case Move::Fire_Blast: return "Fire Blast";
		case Move::Waterfall: return "Waterfall";
		case Move::Clamp: return "Clamp";
		case Move::Swift: return "Swift";
		case Move::Skull_Bash: return "Skull Bash";
		case Move::Spike_Cannon: return "Spike Cannon";
		case Move::Constrict: return "Constrict";
		case Move::Amnesia: return "Amnesia";
		case Move::Kinesis: return "Kinesis";
		case Move::Soft_Boiled: return "Soft-Boiled";
		case Move::High_Jump_Kick: return "High Jump Kick";
		case Move::Glare: return "Glare";
		case Move::Dream_Eater: return "Dream Eater";
		case Move::Poison_Gas: return "Poison Gas";
		case Move::Barrage: return "Barrage";
		case Move::Leech_Life: return "Leech Life";
		case Move::Lovely_Kiss: return "Lovely Kiss";
		case Move::Sky_Attack: return "Sky Attack";
		case Move::Transform: return "Transform";
		case Move::Bubble: return "Bubble";
		case Move::Dizzy_Punch: return "Dizzy Punch";
		case Move::Spore: return "Spore";
		case Move::Flash: return "Flash";
		case Move::Psywave: return "Psywave";
		case Move::Splash: return "Splash";
		case Move::Acid_Armor: return "Acid Armor";
		case Move::Crabhammer: return "Crabhammer";
		case Move::Explosion: return "Explosion";
		case Move::Fury_Swipes: return "Fury Swipes";
		case Move::Bonemerang: return "Bonemerang";
		case Move::Rest: return "Rest";
		case Move::Rock_Slide: return "Rock Slide";
		case Move::Hyper_Fang: return "Hyper Fang";
		case Move::Sharpen: return "Sharpen";
		case Move::Conversion: return "Conversion";
		case Move::Tri_Attack: return "Tri Attack";
		case Move::Super_Fang: return "Super Fang";
		case Move::Slash: return "Slash";
		case Move::Substitute: return "Substitute";
		case Move::Struggle: return "Struggle";
		case Move::Sketch: return "Sketch";
		case Move::Triple_Kick: return "Triple Kick";
		case Move::Thief: return "Thief";
		case Move::Spider_Web: return "Spider Web";
		case Move::Mind_Reader: return "Mind Reader";
		case Move::Nightmare: return "Nightmare";
		case Move::Flame_Wheel: return "Flame Wheel";
		case Move::Snore: return "Snore";
		case Move::Curse: return "Curse";
		case Move::Flail: return "Flail";
		case Move::Conversion_2: return "Conversion 2";
		case Move::Aeroblast: return "Aeroblast";
		case Move::Cotton_Spore: return "Cotton Spore";
		case Move::Reversal: return "Reversal";
		case Move::Spite: return "Spite";
		case Move::Powder_Snow: return "Powder Snow";
		case Move::Protect: return "Protect";
		case Move::Mach_Punch: return "Mach Punch";
		case Move::Scary_Face: return "Scary Face";
		case Move::Feint_Attack: return "Feint Attack";
		case Move::Sweet_Kiss: return "Sweet Kiss";
		case Move::Belly_Drum: return "Belly Drum";
		case Move::Sludge_Bomb: return "Sludge Bomb";
		case Move::Mud_Slap: return "Mud-Slap";
		case Move::Octazooka: return "Octazooka";
		case Move::Spikes: return "Spikes";
		case Move::Zap_Cannon: return "Zap Cannon";
		case Move::Foresight: return "Foresight";
		case Move::Destiny_Bond: return "Destiny Bond";
		case Move::Perish_Song: return "Perish Song";
		case Move::Icy_Wind: return "Icy Wind";
		case Move::Detect: return "Detect";
		case Move::Bone_Rush: return "Bone Rush";
		case Move::Lock_On: return "Lock-On";
		case Move::Outrage: return "Outrage";
		case Move::Sandstorm: return "Sandstorm";
		case Move::Giga_Drain: return "Giga Drain";
		case Move::Endure: return "Endure";
		case Move::Charm: return "Charm";
		case Move::Rollout: return "Rollout";
		case Move::False_Swipe: return "False Swipe";
		case Move::Swagger: return "Swagger";
		case Move::Milk_Drink: return "Milk Drink";
		case Move::Spark: return "Spark";
		case Move::Fury_Cutter: return "Fury Cutter";
		case Move::Steel_Wing: return "Steel Wing";
		case Move::Mean_Look: return "Mean Look";
		case Move::Attract: return "Attract";
		case Move::Sleep_Talk: return "Sleep Talk";
		case Move::Heal_Bell: return "Heal Bell";
		case Move::Return: return "Return";
		case Move::Present: return "Present";
		case Move::Frustration: return "Frustration";
		case Move::Safeguard: return "Safeguard";
		case Move::Pain_Split: return "Pain Split";
		case Move::Sacred_Fire: return "Sacred Fire";
		case Move::Magnitude: return "Magnitude";
		case Move::Dynamic_Punch: return "Dynamic Punch";
		case Move::Megahorn: return "Megahorn";
		case Move::Dragon_Breath: return "Dragon Breath";
		case Move::Baton_Pass: return "Baton Pass";
		case Move::Encore: return "Encore";
		case Move::Pursuit: return "Pursuit";
		case Move::Rapid_Spin: return "Rapid Spin";
		case Move::Sweet_Scent: return "Sweet Scent";
		case Move::Iron_Tail: return "Iron Tail";
		case Move::Metal_Claw: return "Metal Claw";
		case Move::Vital_Throw: return "Vital Throw";
		case Move::Morning_Sun: return "Morning Sun";
		case Move::Synthesis: return "Synthesis";
		case Move::Moonlight: return "Moonlight";
		case Move::Hidden_Power: return "Hidden Power";
		case Move::Cross_Chop: return "Cross Chop";
		case Move::Twister: return "Twister";
		case Move::Rain_Dance: return "Rain Dance";
		case Move::Sunny_Day: return "Sunny Day";
		case Move::Crunch: return "Crunch";
		case Move::Mirror_Coat: return "Mirror Coat";
		case Move::Psych_Up: return "Psych Up";
		case Move::Extreme_Speed: return "Extreme Speed";
		case Move::Ancient_Power: return "Ancient Power";
		case Move::Shadow_Ball: return "Shadow Ball";
		case Move::Future_Sight: return "Future Sight";
		case Move::Rock_Smash: return "Rock Smash";
		case Move::Whirlpool: return "Whirlpool";
		case Move::Beat_Up: return "Beat Up";
		case Move::Fake_Out: return "Fake Out";
		case Move::Uproar: return "Uproar";
		case Move::Stockpile: return "Stockpile";
		case Move::Spit_Up: return "Spit Up";
		case Move::Swallow: return "Swallow";
		case Move::Heat_Wave: return "Heat Wave";
		case Move::Hail: return "Hail";
		case Move::Torment: return "Torment";
		case Move::Flatter: return "Flatter";
		case Move::Will_O_Wisp: return "Will-O-Wisp";
		case Move::Memento: return "Memento";
		case Move::Facade: return "Facade";
		case Move::Focus_Punch: return "Focus Punch";
		case Move::Smelling_Salts: return "Smelling Salts";
		case Move::Follow_Me: return "Follow Me";
		case Move::Nature_Power: return "Nature Power";
		case Move::Charge: return "Charge";
		case Move::Taunt: return "Taunt";
		case Move::Helping_Hand: return "Helping Hand";
		case Move::Trick: return "Trick";
		case Move::Role_Play: return "Role Play";
		case Move::Wish: return "Wish";
		case Move::Assist: return "Assist";
		case Move::Ingrain: return "Ingrain";
		case Move::Superpower: return "Superpower";
		case Move::Magic_Coat: return "Magic Coat";
		case Move::Recycle: return "Recycle";
		case Move::Revenge: return "Revenge";
		case Move::Brick_Break: return "Brick Break";
		case Move::Yawn: return "Yawn";
		case Move::Knock_Off: return "Knock Off";
		case Move::Endeavor: return "Endeavor";
		case Move::Eruption: return "Eruption";
		case Move::Skill_Swap: return "Skill Swap";
		case Move::Imprison: return "Imprison";
		case Move::Refresh: return "Refresh";
		case Move::Grudge: return "Grudge";
		case Move::Snatch: return "Snatch";
		case Move::Secret_Power: return "Secret Power";
		case Move::Dive: return "Dive";
		case Move::Arm_Thrust: return "Arm Thrust";
		case Move::Camouflage: return "Camouflage";
		case Move::Tail_Glow: return "Tail Glow";
		case Move::Luster_Purge: return "Luster Purge";
		case Move::Mist_Ball: return "Mist Ball";
		case Move::Feather_Dance: return "Feather Dance";
		case Move::Teeter_Dance: return "Teeter Dance";
		case Move::Blaze_Kick: return "Blaze Kick";
		case Move::Mud_Sport: return "Mud Sport";
		case Move::Ice_Ball: return "Ice Ball";
		case Move::Needle_Arm: return "Needle Arm";
		case Move::Slack_Off: return "Slack Off";
		case Move::Hyper_Voice: return "Hyper Voice";
		case Move::Poison_Fang: return "Poison Fang";
		case Move::Crush_Claw: return "Crush Claw";
		case Move::Blast_Burn: return "Blast Burn";
		case Move::Hydro_Cannon: return "Hydro Cannon";
		case Move::Meteor_Mash: return "Meteor Mash";
		case Move::Astonish: return "Astonish";
		case Move::Weather_Ball: return "Weather Ball";
		case Move::Aromatherapy: return "Aromatherapy";
		case Move::Fake_Tears: return "Fake Tears";
		case Move::Air_Cutter: return "Air Cutter";
		case Move::Overheat: return "Overheat";
		case Move::Odor_Sleuth: return "Odor Sleuth";
		case Move::Rock_Tomb: return "Rock Tomb";
		case Move::Silver_Wind: return "Silver Wind";
		case Move::Metal_Sound: return "Metal Sound";
		case Move::Grass_Whistle: return "Grass Whistle";
		case Move::Tickle: return "Tickle";
		case Move::Cosmic_Power: return "Cosmic Power";
		case Move::Water_Spout: return "Water Spout";
		case Move::Signal_Beam: return "Signal Beam";
		case Move::Shadow_Punch: return "Shadow Punch";
		case Move::Extrasensory: return "Extrasensory";
		case Move::Sky_Uppercut: return "Sky Uppercut";
		case Move::Sand_Tomb: return "Sand Tomb";
		case Move::Sheer_Cold: return "Sheer Cold";
		case Move::Muddy_Water: return "Muddy Water";
		case Move::Bullet_Seed: return "Bullet Seed";
		case Move::Aerial_Ace: return "Aerial Ace";
		case Move::Icicle_Spear: return "Icicle Spear";
		case Move::Iron_Defense: return "Iron Defense";
		case Move::Block: return "Block";
		case Move::Howl: return "Howl";
		case Move::Dragon_Claw: return "Dragon Claw";
		case Move::Frenzy_Plant: return "Frenzy Plant";
		case Move::Bulk_Up: return "Bulk Up";
		case Move::Bounce: return "Bounce";
		case Move::Mud_Shot: return "Mud Shot";
		case Move::Poison_Tail: return "Poison Tail";
		case Move::Covet: return "Covet";
		case Move::Volt_Tackle: return "Volt Tackle";
		case Move::Magical_Leaf: return "Magical Leaf";
		case Move::Water_Sport: return "Water Sport";
		case Move::Calm_Mind: return "Calm Mind";
		case Move::Leaf_Blade: return "Leaf Blade";
		case Move::Dragon_Dance: return "Dragon Dance";
		case Move::Rock_Blast: return "Rock Blast";
		case Move::Shock_Wave: return "Shock Wave";
		case Move::Water_Pulse: return "Water Pulse";
		case Move::Doom_Desire: return "Doom Desire";
		case Move::Psycho_Boost: return "Psycho Boost";
        default: return "ERROR moves";
    }
}

Move move_from_string(std::string_view const str){
    return Move::Blizzard;
}