#include "species.hpp"

std::string_view to_string(Species const name){
    switch (name) {
		// Generation 1
		case Species::Bulbasaur: return "Bulbasaur";
		case Species::Ivysaur: return "Ivysaur";
		case Species::Venusaur: return "Venusaur";
		case Species::Charmander: return "Charmander";
		case Species::Charmeleon: return "Charmeleon";
		case Species::Charizard: return "Charizard";
		case Species::Squirtle: return "Squirtle";
		case Species::Wartortle: return "Wartortle";
		case Species::Blastoise: return "Blastoise";
		case Species::Caterpie: return "Caterpie";
		case Species::Metapod: return "Metapod";
		case Species::Butterfree: return "Butterfree";
		case Species::Weedle: return "Weedle";
		case Species::Kakuna: return "Kakuna";
		case Species::Beedrill: return "Beedrill";
		case Species::Pidgey: return "Pidgey";
		case Species::Pidgeotto: return "Pidgeotto";
		case Species::Pidgeot: return "Pidgeot";
		case Species::Rattata: return "Rattata";
		case Species::Raticate: return "Raticate";
		case Species::Spearow: return "Spearow";
		case Species::Fearow: return "Fearow";
		case Species::Ekans: return "Ekans";
		case Species::Arbok: return "Arbok";
		case Species::Pikachu: return "Pikachu";
		case Species::Raichu: return "Raichu";
		case Species::Sandshrew: return "Sandshrew";
		case Species::Sandslash: return "Sandslash";
		case Species::Nidoran_F: return "Nidoran-F";
		case Species::Nidorina: return "Nidorina";
		case Species::Nidoqueen: return "Nidoqueen";
		case Species::Nidoran_M: return "Nidoran-M";
		case Species::Nidorino: return "Nidorino";
		case Species::Nidoking: return "Nidoking";
		case Species::Clefairy: return "Clefairy";
		case Species::Clefable: return "Clefable";
		case Species::Vulpix: return "Vulpix";
		case Species::Ninetales: return "Ninetales";
		case Species::Jigglypuff: return "Jigglypuff";
		case Species::Wigglytuff: return "Wigglytuff";
		case Species::Zubat: return "Zubat";
		case Species::Golbat: return "Golbat";
		case Species::Oddish: return "Oddish";
		case Species::Gloom: return "Gloom";
		case Species::Vileplume: return "Vileplume";
		case Species::Paras: return "Paras";
		case Species::Parasect: return "Parasect";
		case Species::Venonat: return "Venonat";
		case Species::Venomoth: return "Venomoth";
		case Species::Diglett: return "Diglett";
		case Species::Dugtrio: return "Dugtrio";
		case Species::Meowth: return "Meowth";
		case Species::Persian: return "Persian";
		case Species::Psyduck: return "Psyduck";
		case Species::Golduck: return "Golduck";
		case Species::Mankey: return "Mankey";
		case Species::Primeape: return "Primeape";
		case Species::Growlithe: return "Growlithe";
		case Species::Arcanine: return "Arcanine";
		case Species::Poliwag: return "Poliwag";
		case Species::Poliwhirl: return "Poliwhirl";
		case Species::Poliwrath: return "Poliwrath";
		case Species::Abra: return "Abra";
		case Species::Kadabra: return "Kadabra";
		case Species::Alakazam: return "Alakazam";
		case Species::Machop: return "Machop";
		case Species::Machoke: return "Machoke";
		case Species::Machamp: return "Machamp";
		case Species::Bellsprout: return "Bellsprout";
		case Species::Weepinbell: return "Weepinbell";
		case Species::Victreebel: return "Victreebel";
		case Species::Tentacool: return "Tentacool";
		case Species::Tentacruel: return "Tentacruel";
		case Species::Geodude: return "Geodude";
		case Species::Graveler: return "Graveler";
		case Species::Golem: return "Golem";
		case Species::Ponyta: return "Ponyta";
		case Species::Rapidash: return "Rapidash";
		case Species::Slowpoke: return "Slowpoke";
		case Species::Slowbro: return "Slowbro";
		case Species::Magnemite: return "Magnemite";
		case Species::Magneton: return "Magneton";
		case Species::Farfetchd: return "Farfetch'd";
		case Species::Doduo: return "Doduo";
		case Species::Dodrio: return "Dodrio";
		case Species::Seel: return "Seel";
		case Species::Dewgong: return "Dewgong";
		case Species::Grimer: return "Grimer";
		case Species::Muk: return "Muk";
		case Species::Shellder: return "Shellder";
		case Species::Cloyster: return "Cloyster";
		case Species::Gastly: return "Gastly";
		case Species::Haunter: return "Haunter";
		case Species::Gengar: return "Gengar";
		case Species::Onix: return "Onix";
		case Species::Drowzee: return "Drowzee";
		case Species::Hypno: return "Hypno";
		case Species::Krabby: return "Krabby";
		case Species::Kingler: return "Kingler";
		case Species::Voltorb: return "Voltorb";
		case Species::Electrode: return "Electrode";
		case Species::Exeggcute: return "Exeggcute";
		case Species::Exeggutor: return "Exeggutor";
		case Species::Cubone: return "Cubone";
		case Species::Marowak: return "Marowak";
		case Species::Hitmonlee: return "Hitmonlee";
		case Species::Hitmonchan: return "Hitmonchan";
		case Species::Lickitung: return "Lickitung";
		case Species::Koffing: return "Koffing";
		case Species::Weezing: return "Weezing";
		case Species::Rhyhorn: return "Rhyhorn";
		case Species::Rhydon: return "Rhydon";
		case Species::Chansey: return "Chansey";
		case Species::Tangela: return "Tangela";
		case Species::Kangaskhan: return "Kangaskhan";
		case Species::Horsea: return "Horsea";
		case Species::Seadra: return "Seadra";
		case Species::Goldeen: return "Goldeen";
		case Species::Seaking: return "Seaking";
		case Species::Staryu: return "Staryu";
		case Species::Starmie: return "Starmie";
		case Species::Mr_Mime: return "Mr. Mime";
		case Species::Scyther: return "Scyther";
		case Species::Jynx: return "Jynx";
		case Species::Electabuzz: return "Electabuzz";
		case Species::Magmar: return "Magmar";
		case Species::Pinsir: return "Pinsir";
		case Species::Tauros: return "Tauros";
		case Species::Magikarp: return "Magikarp";
		case Species::Gyarados: return "Gyarados";
		case Species::Lapras: return "Lapras";
		case Species::Ditto: return "Ditto";
		case Species::Eevee: return "Eevee";
		case Species::Vaporeon: return "Vaporeon";
		case Species::Jolteon: return "Jolteon";
		case Species::Flareon: return "Flareon";
		case Species::Porygon: return "Porygon";
		case Species::Omanyte: return "Omanyte";
		case Species::Omastar: return "Omastar";
		case Species::Kabuto: return "Kabuto";
		case Species::Kabutops: return "Kabutops";
		case Species::Aerodactyl: return "Aerodactyl";
		case Species::Snorlax: return "Snorlax";
		case Species::Articuno: return "Articuno";
		case Species::Zapdos: return "Zapdos";
		case Species::Moltres: return "Moltres";
		case Species::Dratini: return "Dratini";
		case Species::Dragonair: return "Dragonair";
		case Species::Dragonite: return "Dragonite";
		case Species::Mewtwo: return "Mewtwo";
		case Species::Mew: return "Mew";
		
		// Generation 2
		case Species::Chikorita: return "Chikorita";
		case Species::Bayleef: return "Bayleef";
		case Species::Meganium: return "Meganium";
		case Species::Cyndaquil: return "Cyndaquil";
		case Species::Quilava: return "Quilava";
		case Species::Typhlosion: return "Typhlosion";
		case Species::Totodile: return "Totodile";
		case Species::Croconaw: return "Croconaw";
		case Species::Feraligatr: return "Feraligatr";
		case Species::Sentret: return "Sentret";
		case Species::Furret: return "Furret";
		case Species::Hoothoot: return "Hoothoot";
		case Species::Noctowl: return "Noctowl";
		case Species::Ledyba: return "Ledyba";
		case Species::Ledian: return "Ledian";
		case Species::Spinarak: return "Spinarak";
		case Species::Ariados: return "Ariados";
		case Species::Crobat: return "Crobat";
		case Species::Chinchou: return "Chinchou";
		case Species::Lanturn: return "Lanturn";
		case Species::Pichu: return "Pichu";
		case Species::Cleffa: return "Cleffa";
		case Species::Igglybuff: return "Igglybuff";
		case Species::Togepi: return "Togepi";
		case Species::Togetic: return "Togetic";
		case Species::Natu: return "Natu";
		case Species::Xatu: return "Xatu";
		case Species::Mareep: return "Mareep";
		case Species::Flaaffy: return "Flaaffy";
		case Species::Ampharos: return "Ampharos";
		case Species::Bellossom: return "Bellossom";
		case Species::Marill: return "Marill";
		case Species::Azumarill: return "Azumarill";
		case Species::Sudowoodo: return "Sudowoodo";
		case Species::Politoed: return "Politoed";
		case Species::Hoppip: return "Hoppip";
		case Species::Skiploom: return "Skiploom";
		case Species::Jumpluff: return "Jumpluff";
		case Species::Aipom: return "Aipom";
		case Species::Sunkern: return "Sunkern";
		case Species::Sunflora: return "Sunflora";
		case Species::Yanma: return "Yanma";
		case Species::Wooper: return "Wooper";
		case Species::Quagsire: return "Quagsire";
		case Species::Espeon: return "Espeon";
		case Species::Umbreon: return "Umbreon";
		case Species::Murkrow: return "Murkrow";
		case Species::Slowking: return "Slowking";
		case Species::Misdreavus: return "Misdreavus";
		case Species::Unown: return "Unown";
		case Species::Wobbuffet: return "Wobbuffet";
		case Species::Girafarig: return "Girafarig";
		case Species::Pineco: return "Pineco";
		case Species::Forretress: return "Forretress";
		case Species::Dunsparce: return "Dunsparce";
		case Species::Gligar: return "Gligar";
		case Species::Steelix: return "Steelix";
		case Species::Snubbull: return "Snubbull";
		case Species::Granbull: return "Granbull";
		case Species::Qwilfish: return "Qwilfish";
		case Species::Scizor: return "Scizor";
		case Species::Shuckle: return "Shuckle";
		case Species::Heracross: return "Heracross";
		case Species::Sneasel: return "Sneasel";
		case Species::Teddiursa: return "Teddiursa";
		case Species::Ursaring: return "Ursaring";
		case Species::Slugma: return "Slugma";
		case Species::Magcargo: return "Magcargo";
		case Species::Swinub: return "Swinub";
		case Species::Piloswine: return "Piloswine";
		case Species::Corsola: return "Corsola";
		case Species::Remoraid: return "Remoraid";
		case Species::Octillery: return "Octillery";
		case Species::Delibird: return "Delibird";
		case Species::Mantine: return "Mantine";
		case Species::Skarmory: return "Skarmory";
		case Species::Houndour: return "Houndour";
		case Species::Houndoom: return "Houndoom";
		case Species::Kingdra: return "Kingdra";
		case Species::Phanpy: return "Phanpy";
		case Species::Donphan: return "Donphan";
		case Species::Porygon2: return "Porygon2";
		case Species::Stantler: return "Stantler";
		case Species::Smeargle: return "Smeargle";
		case Species::Tyrogue: return "Tyrogue";
		case Species::Hitmontop: return "Hitmontop";
		case Species::Smoochum: return "Smoochum";
		case Species::Elekid: return "Elekid";
		case Species::Magby: return "Magby";
		case Species::Miltank: return "Miltank";
		case Species::Blissey: return "Blissey";
		case Species::Raikou: return "Raikou";
		case Species::Entei: return "Entei";
		case Species::Suicune: return "Suicune";
		case Species::Larvitar: return "Larvitar";
		case Species::Pupitar: return "Pupitar";
		case Species::Tyranitar: return "Tyranitar";
		case Species::Lugia: return "Lugia";
		case Species::Ho_Oh: return "Ho-Oh";
		case Species::Celebi: return "Celebi";
		
		// Generation 3
		case Species::Treecko: return "Treecko";
		case Species::Grovyle: return "Grovyle";
		case Species::Sceptile: return "Sceptile";
		case Species::Torchic: return "Torchic";
		case Species::Combusken: return "Combusken";
		case Species::Blaziken: return "Blaziken";
		case Species::Mudkip: return "Mudkip";
		case Species::Marshtomp: return "Marshtomp";
		case Species::Swampert: return "Swampert";
		case Species::Poochyena: return "Poochyena";
		case Species::Mightyena: return "Mightyena";
		case Species::Zigzagoon: return "Zigzagoon";
		case Species::Linoone: return "Linoone";
		case Species::Wurmple: return "Wurmple";
		case Species::Silcoon: return "Silcoon";
		case Species::Beautifly: return "Beautifly";
		case Species::Cascoon: return "Cascoon";
		case Species::Dustox: return "Dustox";
		case Species::Lotad: return "Lotad";
		case Species::Lombre: return "Lombre";
		case Species::Ludicolo: return "Ludicolo";
		case Species::Seedot: return "Seedot";
		case Species::Nuzleaf: return "Nuzleaf";
		case Species::Shiftry: return "Shiftry";
		case Species::Taillow: return "Taillow";
		case Species::Swellow: return "Swellow";
		case Species::Wingull: return "Wingull";
		case Species::Pelipper: return "Pelipper";
		case Species::Ralts: return "Ralts";
		case Species::Kirlia: return "Kirlia";
		case Species::Gardevoir: return "Gardevoir";
		case Species::Surskit: return "Surskit";
		case Species::Masquerain: return "Masquerain";
		case Species::Shroomish: return "Shroomish";
		case Species::Breloom: return "Breloom";
		case Species::Slakoth: return "Slakoth";
		case Species::Vigoroth: return "Vigoroth";
		case Species::Slaking: return "Slaking";
		case Species::Nincada: return "Nincada";
		case Species::Ninjask: return "Ninjask";
		case Species::Shedinja: return "Shedinja";
		case Species::Whismur: return "Whismur";
		case Species::Loudred: return "Loudred";
		case Species::Exploud: return "Exploud";
		case Species::Makuhita: return "Makuhita";
		case Species::Hariyama: return "Hariyama";
		case Species::Azurill: return "Azurill";
		case Species::Nosepass: return "Nosepass";
		case Species::Skitty: return "Skitty";
		case Species::Delcatty: return "Delcatty";
		case Species::Sableye: return "Sableye";
		case Species::Mawile: return "Mawile";
		case Species::Aron: return "Aron";
		case Species::Lairon: return "Lairon";
		case Species::Aggron: return "Aggron";
		case Species::Meditite: return "Meditite";
		case Species::Medicham: return "Medicham";
		case Species::Electrike: return "Electrike";
		case Species::Manectric: return "Manectric";
		case Species::Plusle: return "Plusle";
		case Species::Minun: return "Minun";
		case Species::Volbeat: return "Volbeat";
		case Species::Illumise: return "Illumise";
		case Species::Roselia: return "Roselia";
		case Species::Gulpin: return "Gulpin";
		case Species::Swalot: return "Swalot";
		case Species::Carvanha: return "Carvanha";
		case Species::Sharpedo: return "Sharpedo";
		case Species::Wailmer: return "Wailmer";
		case Species::Wailord: return "Wailord";
		case Species::Numel: return "Numel";
		case Species::Camerupt: return "Camerupt";
		case Species::Torkoal: return "Torkoal";
		case Species::Spoink: return "Spoink";
		case Species::Grumpig: return "Grumpig";
		case Species::Spinda: return "Spinda";
		case Species::Trapinch: return "Trapinch";
		case Species::Vibrava: return "Vibrava";
		case Species::Flygon: return "Flygon";
		case Species::Cacnea: return "Cacnea";
		case Species::Cacturne: return "Cacturne";
		case Species::Swablu: return "Swablu";
		case Species::Altaria: return "Altaria";
		case Species::Zangoose: return "Zangoose";
		case Species::Seviper: return "Seviper";
		case Species::Lunatone: return "Lunatone";
		case Species::Solrock: return "Solrock";
		case Species::Barboach: return "Barboach";
		case Species::Whiscash: return "Whiscash";
		case Species::Corphish: return "Corphish";
		case Species::Crawdaunt: return "Crawdaunt";
		case Species::Baltoy: return "Baltoy";
		case Species::Claydol: return "Claydol";
		case Species::Lileep: return "Lileep";
		case Species::Cradily: return "Cradily";
		case Species::Anorith: return "Anorith";
		case Species::Armaldo: return "Armaldo";
		case Species::Feebas: return "Feebas";
		case Species::Milotic: return "Milotic";
		case Species::Castform: return "Castform";
		case Species::Kecleon: return "Kecleon";
		case Species::Shuppet: return "Shuppet";
		case Species::Banette: return "Banette";
		case Species::Duskull: return "Duskull";
		case Species::Dusclops: return "Dusclops";
		case Species::Tropius: return "Tropius";
		case Species::Chimecho: return "Chimecho";
		case Species::Absol: return "Absol";
		case Species::Wynaut: return "Wynaut";
		case Species::Snorunt: return "Snorunt";
		case Species::Glalie: return "Glalie";
		case Species::Spheal: return "Spheal";
		case Species::Sealeo: return "Sealeo";
		case Species::Walrein: return "Walrein";
		case Species::Clamperl: return "Clamperl";
		case Species::Huntail: return "Huntail";
		case Species::Gorebyss: return "Gorebyss";
		case Species::Relicanth: return "Relicanth";
		case Species::Luvdisc: return "Luvdisc";
		case Species::Bagon: return "Bagon";
		case Species::Shelgon: return "Shelgon";
		case Species::Salamence: return "Salamence";
		case Species::Beldum: return "Beldum";
		case Species::Metang: return "Metang";
		case Species::Metagross: return "Metagross";
		case Species::Regirock: return "Regirock";
		case Species::Regice: return "Regice";
		case Species::Registeel: return "Registeel";
		case Species::Latias: return "Latias";
		case Species::Latios: return "Latios";
		case Species::Kyogre: return "Kyogre";
		case Species::Groudon: return "Groudon";
		case Species::Rayquaza: return "Rayquaza";
		case Species::Jirachi: return "Jirachi";
		case Species::Deoxys_Normal: return "Deoxys-Normal";
		case Species::Deoxys_Atk: return "Deoxys-Attack";
		case Species::Deoxys_Def: return "Deoxys-Defense";
		case Species::Deoxys_Spe: return "Deoxys-Speed";
        default: return "ERROR species";
    }
}

template<>
auto from_string(std::string_view const str) -> Species{
    static const std::unordered_map<std::string_view, Species> map{
			{ "", Species::None },
			{ "Unrevealed", Species::Unrevealed },
			{ "Abomasnow", Species::Abomasnow },
			{ "Abomasnowmega", Species::Abomasnow },
			{ "Abra", Species::Abra },
			{ "Absol", Species::Absol },
			{ "Absolmega", Species::Absol },
			{ "Accelgor", Species::Accelgor },
			{ "Aegislash", Species::Aegislash },
			{ "Aerodactyl", Species::Aerodactyl },
			{ "Aerodactylmega", Species::Aerodactyl },
			{ "Aggron", Species::Aggron },
			{ "Aggronmega", Species::Aggron },
			{ "Aipom", Species::Aipom },
			{ "Alakazam", Species::Alakazam },
			{ "Alakazammega", Species::Alakazam },
			{ "Alomomola", Species::Alomomola },
			{ "Altaria", Species::Altaria },
			{ "Altariamega", Species::Altaria },
			{ "Amaura", Species::Amaura },
			{ "Ambipom", Species::Ambipom },
			{ "Amoonguss", Species::Amoonguss },
			{ "Ampharos", Species::Ampharos },
			{ "Ampharosmega", Species::Ampharos },
			{ "Anorith", Species::Anorith },
			{ "Araquanid", Species::Araquanid },
			{ "Araquanidtotem", Species::Araquanid },
			{ "Arbok", Species::Arbok },
			{ "Arcanine", Species::Arcanine },
			{ "Arceus", Species::Arceus },
			{ "Arceusbug", Species::Arceus },
			{ "Arceusdark", Species::Arceus },
			{ "Arceusdragon", Species::Arceus },
			{ "Arceuselectric", Species::Arceus },
			{ "Arceusfighting", Species::Arceus },
			{ "Arceusfire", Species::Arceus },
			{ "Arceusflying", Species::Arceus },
			{ "Arceusghost", Species::Arceus },
			{ "Arceusgrass", Species::Arceus },
			{ "Arceusground", Species::Arceus },
			{ "Arceusice", Species::Arceus },
			{ "Arceusnormal", Species::Arceus },
			{ "Arceuspoison", Species::Arceus },
			{ "Arceuspsychic", Species::Arceus },
			{ "Arceusrock", Species::Arceus },
			{ "Arceussteel", Species::Arceus },
			{ "Arceuswater", Species::Arceus },
			{ "Archen", Species::Archen },
			{ "Archeops", Species::Archeops },
			{ "Ariados", Species::Ariados },
			{ "Armaldo", Species::Armaldo },
			{ "Aromatisse", Species::Aromatisse },
			{ "Aron", Species::Aron },
			{ "Articuno", Species::Articuno },
			{ "Audino", Species::Audino },
			{ "Audinomega", Species::Audino },
			{ "Aurorus", Species::Aurorus },
			{ "Avalugg", Species::Avalugg },
			{ "Axew", Species::Axew },
			{ "Azelf", Species::Azelf },
			{ "Azumarill", Species::Azumarill },
			{ "Azurill", Species::Azurill },
			{ "Bagon", Species::Bagon },
			{ "Baltoy", Species::Baltoy },
			{ "Banette", Species::Banette },
			{ "Banettemega", Species::Banette },
			{ "Barbaracle", Species::Barbaracle },
			{ "Barboach", Species::Barboach },
			{ "Basculin", Species::Basculin },
			{ "Bastiodon", Species::Bastiodon },
			{ "Bayleef", Species::Bayleef },
			{ "Beartic", Species::Beartic },
			{ "Beautifly", Species::Beautifly },
			{ "Beedrill", Species::Beedrill },
			{ "Beedrillmega", Species::Beedrill },
			{ "Beheeyem", Species::Beheeyem },
			{ "Beldum", Species::Beldum },
			{ "Bellossom", Species::Bellossom },
			{ "Bellsprout", Species::Bellsprout },
			{ "Bergmite", Species::Bergmite },
			{ "Bewear", Species::Bewear },
			{ "Bibarel", Species::Bibarel },
			{ "Bidoof", Species::Bidoof },
			{ "Binacle", Species::Binacle },
			{ "Bisharp", Species::Bisharp },
			{ "Blacephalon", Species::Blacephalon },
			{ "Blastoise", Species::Blastoise },
			{ "Blastoisemega", Species::Blastoise },
			{ "Blaziken", Species::Blaziken },
			{ "Blissey", Species::Blissey },
			{ "Blitzle", Species::Blitzle },
			{ "Boldore", Species::Boldore },
			{ "Bonsly", Species::Bonsly },
			{ "Bouffalant", Species::Bouffalant },
			{ "Bounsweet", Species::Bounsweet },
			{ "Braixen", Species::Braixen },
			{ "Braviary", Species::Braviary },
			{ "Breloom", Species::Breloom },
			{ "Brionne", Species::Brionne },
			{ "Bronzong", Species::Bronzong },
			{ "Bronzor", Species::Bronzor },
			{ "Bruxish", Species::Bruxish },
			{ "Budew", Species::Budew },
			{ "Buizel", Species::Buizel },
			{ "Bulbasaur", Species::Bulbasaur },
			{ "Buneary", Species::Buneary },
			{ "Bunnelby", Species::Bunnelby },
			{ "Burmy", Species::Burmy },
			{ "Butterfree", Species::Butterfree },
			{ "Buzzwole", Species::Buzzwole },
			{ "Cacnea", Species::Cacnea },
			{ "Cacturne", Species::Cacturne },
			{ "Camerupt", Species::Camerupt },
			{ "Cameruptmega", Species::Camerupt },
			{ "Carbink", Species::Carbink },
			{ "Carnivine", Species::Carnivine },
			{ "Carracosta", Species::Carracosta },
			{ "Carvanha", Species::Carvanha },
			{ "Cascoon", Species::Cascoon },
			{ "Castform", Species::Castform },
			{ "Caterpie", Species::Caterpie },
			{ "Celebi", Species::Celebi },
			{ "Celesteela", Species::Celesteela },
			{ "Chandelure", Species::Chandelure },
			{ "Chansey", Species::Chansey },
			{ "Charizard", Species::Charizard },
			{ "Charizardmegax", Species::Charizard },
			{ "Charizardmegay", Species::Charizard },
			{ "Charjabug", Species::Charjabug },
			{ "Charmander", Species::Charmander },
			{ "Charmeleon", Species::Charmeleon },
			{ "Chatot", Species::Chatot },
			{ "Cherrim", Species::Cherrim },
			{ "Cherubi", Species::Cherubi },
			{ "Chesnaught", Species::Chesnaught },
			{ "Chespin", Species::Chespin },
			{ "Chikorita", Species::Chikorita },
			{ "Chimchar", Species::Chimchar },
			{ "Chimecho", Species::Chimecho },
			{ "Chinchou", Species::Chinchou },
			{ "Chingling", Species::Chingling },
			{ "Cinccino", Species::Cinccino },
			{ "Clamperl", Species::Clamperl },
			{ "Clauncher", Species::Clauncher },
			{ "Clawitzer", Species::Clawitzer },
			{ "Claydol", Species::Claydol },
			{ "Clefable", Species::Clefable },
			{ "Clefairy", Species::Clefairy },
			{ "Cleffa", Species::Cleffa },
			{ "Cloyster", Species::Cloyster },
			{ "Cobalion", Species::Cobalion },
			{ "Cofagrigus", Species::Cofagrigus },
			{ "Combee", Species::Combee },
			{ "Combusken", Species::Combusken },
			{ "Comfey", Species::Comfey },
			{ "Conkeldurr", Species::Conkeldurr },
			{ "Corphish", Species::Corphish },
			{ "Corsola", Species::Corsola },
			{ "Cosmoem", Species::Cosmoem },
			{ "Cosmog", Species::Cosmog },
			{ "Cottonee", Species::Cottonee },
			{ "Crabominable", Species::Crabominable },
			{ "Crabrawler", Species::Crabrawler },
			{ "Cradily", Species::Cradily },
			{ "Cranidos", Species::Cranidos },
			{ "Crawdaunt", Species::Crawdaunt },
			{ "Cresselia", Species::Cresselia },
			{ "Croagunk", Species::Croagunk },
			{ "Crobat", Species::Crobat },
			{ "Croconaw", Species::Croconaw },
			{ "Crustle", Species::Crustle },
			{ "Cryogonal", Species::Cryogonal },
			{ "Cubchoo", Species::Cubchoo },
			{ "Cubone", Species::Cubone },
			{ "Cutiefly", Species::Cutiefly },
			{ "Cyndaquil", Species::Cyndaquil },
			{ "Darkrai", Species::Darkrai },
			{ "Darmanitan", Species::Darmanitan },
			{ "Dartrix", Species::Dartrix },
			{ "Darumaka", Species::Darumaka },
			{ "Decidueye", Species::Decidueye },
			{ "Dedenne", Species::Dedenne },
			{ "Deerling", Species::Deerling },
			{ "Deino", Species::Deino },
			{ "Delcatty", Species::Delcatty },
			{ "Delibird", Species::Delibird },
			{ "Delphox", Species::Delphox },
			{ "Deoxys", Species::Deoxys_Normal },
			{ "Deoxysattack", Species::Deoxys_Atk },
			{ "Deoxysdefense", Species::Deoxys_Def },
			{ "Deoxysnormal", Species::Deoxys_Normal },
			{ "Deoxysspeed", Species::Deoxys_Spe },
			{ "Dewgong", Species::Dewgong },
			{ "Dewott", Species::Dewott },
			{ "Dewpider", Species::Dewpider },
			{ "Dhelmise", Species::Dhelmise },
			{ "Dialga", Species::Dialga },
			{ "Diancie", Species::Diancie },
			{ "Dianciemega", Species::Diancie },
			{ "Diggersby", Species::Diggersby },
			{ "Diglett", Species::Diglett },
			{ "Diglettalola", Species::Diglett_Alolan },
			{ "Diglettalolan", Species::Diglett_Alolan },
			{ "Ditto", Species::Ditto },
			{ "Dodrio", Species::Dodrio },
			{ "Doduo", Species::Doduo },
			{ "Donphan", Species::Donphan },
			{ "Doublade", Species::Doublade },
			{ "Dragalge", Species::Dragalge },
			{ "Dragonair", Species::Dragonair },
			{ "Dragonite", Species::Dragonite },
			{ "Drampa", Species::Drampa },
			{ "Drapion", Species::Drapion },
			{ "Dratini", Species::Dratini },
			{ "Drifblim", Species::Drifblim },
			{ "Drifloon", Species::Drifloon },
			{ "Drilbur", Species::Drilbur },
			{ "Drowzee", Species::Drowzee },
			{ "Druddigon", Species::Druddigon },
			{ "Ducklett", Species::Ducklett },
			{ "Dugtrio", Species::Dugtrio },
			{ "Dugtrioalola", Species::Dugtrio_Alolan },
			{ "Dugtrioalolan", Species::Dugtrio_Alolan },
			{ "Dunsparce", Species::Dunsparce },
			{ "Duosion", Species::Duosion },
			{ "Durant", Species::Durant },
			{ "Dusclops", Species::Dusclops },
			{ "Dusknoir", Species::Dusknoir },
			{ "Duskull", Species::Duskull },
			{ "Dustox", Species::Dustox },
			{ "Dwebble", Species::Dwebble },
			{ "Eelektrik", Species::Eelektrik },
			{ "Eelektross", Species::Eelektross },
			{ "Eevee", Species::Eevee },
			{ "Ekans", Species::Ekans },
			{ "Electabuzz", Species::Electabuzz },
			{ "Electivire", Species::Electivire },
			{ "Electrike", Species::Electrike },
			{ "Electrode", Species::Electrode },
			{ "Elekid", Species::Elekid },
			{ "Elgyem", Species::Elgyem },
			{ "Emboar", Species::Emboar },
			{ "Emolga", Species::Emolga },
			{ "Empoleon", Species::Empoleon },
			{ "Entei", Species::Entei },
			{ "Escavalier", Species::Escavalier },
			{ "Espeon", Species::Espeon },
			{ "Espurr", Species::Espurr },
			{ "Excadrill", Species::Excadrill },
			{ "Exeggcute", Species::Exeggcute },
			{ "Exeggutor", Species::Exeggutor },
			{ "Exeggutoralola", Species::Exeggutor_Alolan },
			{ "Exeggutoralolan", Species::Exeggutor_Alolan },
			{ "Exploud", Species::Exploud },
			{ "Farfetchd", Species::Farfetchd },
			{ "Fearow", Species::Fearow },
			{ "Feebas", Species::Feebas },
			{ "Fennekin", Species::Fennekin },
			{ "Feraligatr", Species::Feraligatr },
			{ "Ferroseed", Species::Ferroseed },
			{ "Ferrothorn", Species::Ferrothorn },
			{ "Finneon", Species::Finneon },
			{ "Flaaffy", Species::Flaaffy },
			{ "Flabebe", Species::Flabebe },
			{ "Flareon", Species::Flareon },
			{ "Fletchinder", Species::Fletchinder },
			{ "Fletchling", Species::Fletchling },
			{ "Floatzel", Species::Floatzel },
			{ "Floette", Species::Floette },
			{ "Florges", Species::Florges },
			{ "Flygon", Species::Flygon },
			{ "Fomantis", Species::Fomantis },
			{ "Foongus", Species::Foongus },
			{ "Forretress", Species::Forretress },
			{ "Fraxure", Species::Fraxure },
			{ "Frillish", Species::Frillish },
			{ "Froakie", Species::Froakie },
			{ "Frogadier", Species::Frogadier },
			{ "Froslass", Species::Froslass },
			{ "Furfrou", Species::Furfrou },
			{ "Furret", Species::Furret },
			{ "Gabite", Species::Gabite },
			{ "Gallade", Species::Gallade },
			{ "Gallademega", Species::Gallade },
			{ "Galvantula", Species::Galvantula },
			{ "Garbodor", Species::Garbodor },
			{ "Garchomp", Species::Garchomp },
			{ "Garchompmega", Species::Garchomp },
			{ "Gardevoir", Species::Gardevoir },
			{ "Gardevoirmega", Species::Gardevoir },
			{ "Gastly", Species::Gastly },
			{ "Gastrodon", Species::Gastrodon },
			{ "Genesect", Species::Genesect },
			{ "Gengar", Species::Gengar },
			{ "Geodude", Species::Geodude },
			{ "Geodudealola", Species::Geodude_Alolan },
			{ "Geodudealolan", Species::Geodude_Alolan },
			{ "Gible", Species::Gible },
			{ "Gigalith", Species::Gigalith },
			{ "Girafarig", Species::Girafarig },
			{ "Giratina", Species::Giratina_Altered },
			{ "Giratinaaltered", Species::Giratina_Altered },
			{ "Giratinaorigin", Species::Giratina_Origin },
			{ "Glaceon", Species::Glaceon },
			{ "Glalie", Species::Glalie },
			{ "Glaliemega", Species::Glalie },
			{ "Glameow", Species::Glameow },
			{ "Gligar", Species::Gligar },
			{ "Gliscor", Species::Gliscor },
			{ "Gloom", Species::Gloom },
			{ "Gogoat", Species::Gogoat },
			{ "Golbat", Species::Golbat },
			{ "Goldeen", Species::Goldeen },
			{ "Golduck", Species::Golduck },
			{ "Golem", Species::Golem },
			{ "Golemalola", Species::Golem_Alolan },
			{ "Golemalolan", Species::Golem_Alolan },
			{ "Golett", Species::Golett },
			{ "Golisopod", Species::Golisopod },
			{ "Golurk", Species::Golurk },
			{ "Goodra", Species::Goodra },
			{ "Goomy", Species::Goomy },
			{ "Gorebyss", Species::Gorebyss },
			{ "Gothita", Species::Gothita },
			{ "Gothitelle", Species::Gothitelle },
			{ "Gothorita", Species::Gothorita },
			{ "Gourgeist", Species::Gourgeist_Average },
			{ "Gourgeistaverage", Species::Gourgeist_Average },
			{ "Gourgeistlarge", Species::Gourgeist_Large },
			{ "Gourgeistsmall", Species::Gourgeist_Small },
			{ "Gourgeistsuper", Species::Gourgeist_Super },
			{ "Granbull", Species::Granbull },
			{ "Graveler", Species::Graveler },
			{ "Graveleralola", Species::Graveler_Alolan },
			{ "Graveleralolan", Species::Graveler_Alolan },
			{ "Greninja", Species::Greninja },
			{ "Greninjaash", Species::Greninja },
			{ "Grimer", Species::Grimer },
			{ "Grimeralola", Species::Grimer_Alolan },
			{ "Grimeralolan", Species::Grimer_Alolan },
			{ "Grotle", Species::Grotle },
			{ "Groudon", Species::Groudon },
			{ "Grovyle", Species::Grovyle },
			{ "Growlithe", Species::Growlithe },
			{ "Grubbin", Species::Grubbin },
			{ "Grumpig", Species::Grumpig },
			{ "Gulpin", Species::Gulpin },
			{ "Gumshoos", Species::Gumshoos },
			// TODO: ???
			{ "Gumshoostotem", Species::Gumshoos },
			{ "Gurdurr", Species::Gurdurr },
			{ "Guzzlord", Species::Guzzlord },
			{ "Gyarados", Species::Gyarados },
			{ "Gyaradosmega", Species::Gyarados },
			{ "Hakamoo", Species::Hakamo_o },
			{ "Happiny", Species::Happiny },
			{ "Hariyama", Species::Hariyama },
			{ "Haunter", Species::Haunter },
			{ "Hawlucha", Species::Hawlucha },
			{ "Haxorus", Species::Haxorus },
			{ "Heatmor", Species::Heatmor },
			{ "Heatran", Species::Heatran },
			{ "Heliolisk", Species::Heliolisk },
			{ "Helioptile", Species::Helioptile },
			{ "Heracross", Species::Heracross },
			{ "Heracrossmega", Species::Heracross },
			{ "Herdier", Species::Herdier },
			{ "Hippopotas", Species::Hippopotas },
			{ "Hippowdon", Species::Hippowdon },
			{ "Hitmonchan", Species::Hitmonchan },
			{ "Hitmonlee", Species::Hitmonlee },
			{ "Hitmontop", Species::Hitmontop },
			{ "Honchkrow", Species::Honchkrow },
			{ "Honedge", Species::Honedge },
			{ "Hooh", Species::Ho_Oh },
			{ "Hoopa", Species::Hoopa_Confined },
			{ "Hoopaconfined", Species::Hoopa_Confined },
			{ "Hoopaunbound", Species::Hoopa_Unbound },
			{ "Hoothoot", Species::Hoothoot },
			{ "Hoppip", Species::Hoppip },
			{ "Horsea", Species::Horsea },
			{ "Houndoom", Species::Houndoom },
			{ "Houndoommega", Species::Houndoom },
			{ "Houndour", Species::Houndour },
			{ "Huntail", Species::Huntail },
			{ "Hydreigon", Species::Hydreigon },
			{ "Hypno", Species::Hypno },
			{ "Igglybuff", Species::Igglybuff },
			{ "Illumise", Species::Illumise },
			{ "Incineroar", Species::Incineroar },
			{ "Infernape", Species::Infernape },
			{ "Inkay", Species::Inkay },
			{ "Ivysaur", Species::Ivysaur },
			{ "Jangmoo", Species::Jangmo_o },
			{ "Jellicent", Species::Jellicent },
			{ "Jigglypuff", Species::Jigglypuff },
			{ "Jirachi", Species::Jirachi },
			{ "Jolteon", Species::Jolteon },
			{ "Joltik", Species::Joltik },
			{ "Jumpluff", Species::Jumpluff },
			{ "Jynx", Species::Jynx },
			{ "Kabuto", Species::Kabuto },
			{ "Kabutops", Species::Kabutops },
			{ "Kadabra", Species::Kadabra },
			{ "Kakuna", Species::Kakuna },
			{ "Kangaskhan", Species::Kangaskhan },
			{ "Karrablast", Species::Karrablast },
			{ "Kartana", Species::Kartana },
			{ "Kecleon", Species::Kecleon },
			{ "Keldeo", Species::Keldeo },
			{ "Kingdra", Species::Kingdra },
			{ "Kingler", Species::Kingler },
			{ "Kirlia", Species::Kirlia },
			{ "Klang", Species::Klang },
			{ "Klefki", Species::Klefki },
			{ "Klink", Species::Klink },
			{ "Klinklang", Species::Klinklang },
			{ "Koffing", Species::Koffing },
			{ "Komala", Species::Komala },
			{ "Kommoo", Species::Kommo_o },
			{ "Kommoototem", Species::Kommo_o },
			{ "Krabby", Species::Krabby },
			{ "Kricketot", Species::Kricketot },
			{ "Kricketune", Species::Kricketune },
			{ "Krokorok", Species::Krokorok },
			{ "Krookodile", Species::Krookodile },
			{ "Kyogre", Species::Kyogre },
			{ "Kyurem", Species::Kyurem },
			{ "Kyuremblack", Species::Kyurem_Black },
			{ "Kyuremwhite", Species::Kyurem_White },
			{ "Lairon", Species::Lairon },
			{ "Lampent", Species::Lampent },
			{ "Landorus", Species::Landorus_Incarnate },
			{ "Landorusincarnate", Species::Landorus_Incarnate },
			{ "Landorustherian", Species::Landorus_Therian },
			{ "Lanturn", Species::Lanturn },
			{ "Lapras", Species::Lapras },
			{ "Larvesta", Species::Larvesta },
			{ "Larvitar", Species::Larvitar },
			{ "Latias", Species::Latias },
			{ "Latiasmega", Species::Latias },
			{ "Latios", Species::Latios },
			{ "Latiosmega", Species::Latios },
			{ "Leafeon", Species::Leafeon },
			{ "Leavanny", Species::Leavanny },
			{ "Ledian", Species::Ledian },
			{ "Ledyba", Species::Ledyba },
			{ "Lickilicky", Species::Lickilicky },
			{ "Lickitung", Species::Lickitung },
			{ "Liepard", Species::Liepard },
			{ "Lileep", Species::Lileep },
			{ "Lilligant", Species::Lilligant },
			{ "Lillipup", Species::Lillipup },
			{ "Linoone", Species::Linoone },
			{ "Litleo", Species::Litleo },
			{ "Litten", Species::Litten },
			{ "Litwick", Species::Litwick },
			{ "Lombre", Species::Lombre },
			{ "Lopunny", Species::Lopunny },
			{ "Lopunnymega", Species::Lopunny },
			{ "Lotad", Species::Lotad },
			{ "Loudred", Species::Loudred },
			{ "Lucario", Species::Lucario },
			{ "Ludicolo", Species::Ludicolo },
			{ "Lugia", Species::Lugia },
			{ "Lumineon", Species::Lumineon },
			{ "Lunala", Species::Lunala },
			{ "Lunatone", Species::Lunatone },
			{ "Lurantis", Species::Lurantis },
			{ "Lurantistotem", Species::Lurantis },
			{ "Luvdisc", Species::Luvdisc },
			{ "Luxio", Species::Luxio },
			{ "Luxray", Species::Luxray },
			{ "Lycanroc", Species::Lycanroc_Midday },
			{ "Lycanrocdusk", Species::Lycanroc_Dusk },
			{ "Lycanrocmidday", Species::Lycanroc_Midday },
			{ "Lycanrocmidnight", Species::Lycanroc_Midnight },
			{ "Machamp", Species::Machamp },
			{ "Machoke", Species::Machoke },
			{ "Machop", Species::Machop },
			{ "Magby", Species::Magby },
			{ "Magcargo", Species::Magcargo },
			{ "Magearna", Species::Magearna },
			{ "Magikarp", Species::Magikarp },
			{ "Magmar", Species::Magmar },
			{ "Magmortar", Species::Magmortar },
			{ "Magnemite", Species::Magnemite },
			{ "Magneton", Species::Magneton },
			{ "Magnezone", Species::Magnezone },
			{ "Makuhita", Species::Makuhita },
			{ "Malamar", Species::Malamar },
			{ "Mamoswine", Species::Mamoswine },
			{ "Manaphy", Species::Manaphy },
			{ "Mandibuzz", Species::Mandibuzz },
			{ "Manectric", Species::Manectric },
			{ "Manectricmega", Species::Manectric },
			{ "Mankey", Species::Mankey },
			{ "Mantine", Species::Mantine },
			{ "Mantyke", Species::Mantyke },
			{ "Maractus", Species::Maractus },
			{ "Mareanie", Species::Mareanie },
			{ "Mareep", Species::Mareep },
			{ "Marill", Species::Marill },
			{ "Marowak", Species::Marowak },
			{ "Marowakalola", Species::Marowak_Alolan },
			{ "Marowakalolan", Species::Marowak_Alolan },
			{ "Marowakalolatotem", Species::Marowak_Alolan },
			{ "Marshadow", Species::Marshadow },
			{ "Marshtomp", Species::Marshtomp },
			{ "Masquerain", Species::Masquerain },
			{ "Mawile", Species::Mawile },
			{ "Mawilemega", Species::Mawile },
			{ "Medicham", Species::Medicham },
			{ "Medichammega", Species::Medicham },
			{ "Meditite", Species::Meditite },
			{ "Meganium", Species::Meganium },
			{ "Meloetta", Species::Meloetta },
			{ "Meowstic", Species::Meowstic },
			{ "Meowth", Species::Meowth },
			{ "Meowthalola", Species::Meowth_Alolan },
			{ "Meowthalolan", Species::Meowth_Alolan },
			{ "Mesprit", Species::Mesprit },
			{ "Metagross", Species::Metagross },
			{ "Metagrossmega", Species::Metagross },
			{ "Metang", Species::Metang },
			{ "Metapod", Species::Metapod },
			{ "Mew", Species::Mew },
			{ "Mewtwo", Species::Mewtwo },
			{ "Mienfoo", Species::Mienfoo },
			{ "Mienshao", Species::Mienshao },
			{ "Mightyena", Species::Mightyena },
			{ "Milotic", Species::Milotic },
			{ "Miltank", Species::Miltank },
			{ "Mimejr", Species::Mime_Jr },
			{ "Mimikyu", Species::Mimikyu },
			{ "Mimikyutotem", Species::Mimikyu },
			{ "Minccino", Species::Minccino },
			{ "Minior", Species::Minior_Core },
			{ "Miniorcore", Species::Minior_Core },
			{ "Miniormeteor", Species::Minior_Meteor },
			{ "Minun", Species::Minun },
			{ "Misdreavus", Species::Misdreavus },
			{ "Mismagius", Species::Mismagius },
			{ "Moltres", Species::Moltres },
			{ "Monferno", Species::Monferno },
			{ "Morelull", Species::Morelull },
			{ "Mothim", Species::Mothim },
			{ "Mrmime", Species::Mr_Mime },
			{ "Mudbray", Species::Mudbray },
			{ "Mudkip", Species::Mudkip },
			{ "Mudsdale", Species::Mudsdale },
			{ "Muk", Species::Muk },
			{ "Mukalola", Species::Muk_Alolan },
			{ "Mukalolan", Species::Muk_Alolan },
			{ "Munchlax", Species::Munchlax },
			{ "Munna", Species::Munna },
			{ "Murkrow", Species::Murkrow },
			{ "Musharna", Species::Musharna },
			{ "Naganadel", Species::Naganadel },
			{ "Natu", Species::Natu },
			{ "Necrozma", Species::Necrozma },
			{ "Necrozmadawnwings", Species::Necrozma_Dawn_Wings },
			{ "Necrozmaduskmane", Species::Necrozma_Dusk_Mane },
			{ "Necrozmaultra", Species::Necrozma_Ultra },
			{ "Nidoking", Species::Nidoking },
			{ "Nidoqueen", Species::Nidoqueen },
			{ "Nidoranf", Species::Nidoran_F },
			{ "Nidoranm", Species::Nidoran_M },
			{ "Nidorina", Species::Nidorina },
			{ "Nidorino", Species::Nidorino },
			{ "Nihilego", Species::Nihilego },
			{ "Nincada", Species::Nincada },
			{ "Ninetales", Species::Ninetales },
			{ "Ninetalesalola", Species::Ninetales_Alolan },
			{ "Ninetalesalolan", Species::Ninetales_Alolan },
			{ "Ninjask", Species::Ninjask },
			{ "Noctowl", Species::Noctowl },
			{ "Noibat", Species::Noibat },
			{ "Noivern", Species::Noivern },
			{ "Nosepass", Species::Nosepass },
			{ "Numel", Species::Numel },
			{ "Nuzleaf", Species::Nuzleaf },
			{ "Octillery", Species::Octillery },
			{ "Oddish", Species::Oddish },
			{ "Omanyte", Species::Omanyte },
			{ "Omastar", Species::Omastar },
			{ "Onix", Species::Onix },
			{ "Oranguru", Species::Oranguru },
			{ "Oricorio", Species::Oricorio },
			{ "Oricoriopau", Species::Oricorio_Pau },
			{ "Oricoriopompom", Species::Oricorio_Pom_Pom },
			{ "Oricoriosensu", Species::Oricorio_Sensu },
			{ "Oshawott", Species::Oshawott },
			{ "Pachirisu", Species::Pachirisu },
			{ "Palkia", Species::Palkia },
			{ "Palossand", Species::Palossand },
			{ "Palpitoad", Species::Palpitoad },
			{ "Pancham", Species::Pancham },
			{ "Pangoro", Species::Pangoro },
			{ "Panpour", Species::Panpour },
			{ "Pansage", Species::Pansage },
			{ "Pansear", Species::Pansear },
			{ "Paras", Species::Paras },
			{ "Parasect", Species::Parasect },
			{ "Passimian", Species::Passimian },
			{ "Patrat", Species::Patrat },
			{ "Pawniard", Species::Pawniard },
			{ "Pelipper", Species::Pelipper },
			{ "Persian", Species::Persian },
			{ "Persianalola", Species::Persian_Alolan },
			{ "Persianalolan", Species::Persian_Alolan },
			{ "Petilil", Species::Petilil },
			{ "Phanpy", Species::Phanpy },
			{ "Phantump", Species::Phantump },
			{ "Pheromosa", Species::Pheromosa },
			{ "Phione", Species::Phione },
			{ "Pichu", Species::Pichu },
			{ "Pidgeot", Species::Pidgeot },
			{ "Pidgeotmega", Species::Pidgeot },
			{ "Pidgeotto", Species::Pidgeotto },
			{ "Pidgey", Species::Pidgey },
			{ "Pidove", Species::Pidove },
			{ "Pignite", Species::Pignite },
			{ "Pikachu", Species::Pikachu },
			{ "Pikipek", Species::Pikipek },
			{ "Piloswine", Species::Piloswine },
			{ "Pineco", Species::Pineco },
			{ "Pinsir", Species::Pinsir },
			{ "Pinsirmega", Species::Pinsir },
			{ "Piplup", Species::Piplup },
			{ "Plusle", Species::Plusle },
			{ "Poipole", Species::Poipole },
			{ "Politoed", Species::Politoed },
			{ "Poliwag", Species::Poliwag },
			{ "Poliwhirl", Species::Poliwhirl },
			{ "Poliwrath", Species::Poliwrath },
			{ "Ponyta", Species::Ponyta },
			{ "Poochyena", Species::Poochyena },
			{ "Popplio", Species::Popplio },
			{ "Porygon", Species::Porygon },
			{ "Porygon2", Species::Porygon2 },
			{ "Porygonz", Species::Porygon_Z },
			{ "Primarina", Species::Primarina },
			{ "Primeape", Species::Primeape },
			{ "Prinplup", Species::Prinplup },
			{ "Probopass", Species::Probopass },
			{ "Psyduck", Species::Psyduck },
			{ "Pumpkaboo", Species::Pumpkaboo_Average },
			{ "Pumpkabooaverage", Species::Pumpkaboo_Average },
			{ "Pumpkaboolarge", Species::Pumpkaboo_Large },
			{ "Pumpkaboosmall", Species::Pumpkaboo_Small },
			{ "Pumpkaboosuper", Species::Pumpkaboo_Super },
			{ "Pupitar", Species::Pupitar },
			{ "Purrloin", Species::Purrloin },
			{ "Purugly", Species::Purugly },
			{ "Pyroar", Species::Pyroar },
			{ "Pyukumuku", Species::Pyukumuku },
			{ "Quagsire", Species::Quagsire },
			{ "Quilava", Species::Quilava },
			{ "Quilladin", Species::Quilladin },
			{ "Qwilfish", Species::Qwilfish },
			{ "Raichu", Species::Raichu },
			{ "Raichualola", Species::Raichu_Alolan },
			{ "Raichualolan", Species::Raichu_Alolan },
			{ "Raikou", Species::Raikou },
			{ "Ralts", Species::Ralts },
			{ "Rampardos", Species::Rampardos },
			{ "Rapidash", Species::Rapidash },
			{ "Raticate", Species::Raticate },
			{ "Raticatealola", Species::Raticate_Alolan },
			{ "Raticatealolan", Species::Raticate_Alolan },
			{ "Raticatealolatotem", Species::Raticate_Alolan },
			{ "Rattata", Species::Rattata },
			{ "Rattataalola", Species::Rattata_Alolan },
			{ "Rattataalolan", Species::Rattata_Alolan },
			{ "Rayquaza", Species::Rayquaza },
			{ "Regice", Species::Regice },
			{ "Regigigas", Species::Regigigas },
			{ "Regirock", Species::Regirock },
			{ "Registeel", Species::Registeel },
			{ "Relicanth", Species::Relicanth },
			{ "Remoraid", Species::Remoraid },
			{ "Reshiram", Species::Reshiram },
			{ "Reuniclus", Species::Reuniclus },
			{ "Rhydon", Species::Rhydon },
			{ "Rhyhorn", Species::Rhyhorn },
			{ "Rhyperior", Species::Rhyperior },
			{ "Ribombee", Species::Ribombee },
			{ "Ribombeetotem", Species::Ribombee },
			{ "Riolu", Species::Riolu },
			{ "Rockruff", Species::Rockruff },
			{ "Roggenrola", Species::Roggenrola },
			{ "Roselia", Species::Roselia },
			{ "Roserade", Species::Roserade },
			{ "Rotom", Species::Rotom },
			{ "Rotomfan", Species::Rotom_Fan },
			{ "Rotomfrost", Species::Rotom_Frost },
			{ "Rotomheat", Species::Rotom_Heat },
			{ "Rotommow", Species::Rotom_Mow },
			{ "Rotomwash", Species::Rotom_Wash },
			{ "Rowlet", Species::Rowlet },
			{ "Rufflet", Species::Rufflet },
			{ "Sableye", Species::Sableye },
			{ "Sableyemega", Species::Sableye },
			{ "Salamence", Species::Salamence },
			{ "Salandit", Species::Salandit },
			{ "Salazzle", Species::Salazzle },
			{ "Salazzletotem", Species::Salazzle },
			{ "Samurott", Species::Samurott },
			{ "Sandile", Species::Sandile },
			{ "Sandshrew", Species::Sandshrew },
			{ "Sandshrewalola", Species::Sandshrew_Alolan },
			{ "Sandshrewalolan", Species::Sandshrew_Alolan },
			{ "Sandslash", Species::Sandslash },
			{ "Sandslashalola", Species::Sandslash_Alolan },
			{ "Sandslashalolan", Species::Sandslash_Alolan },
			{ "Sandygast", Species::Sandygast },
			{ "Sawk", Species::Sawk },
			{ "Sawsbuck", Species::Sawsbuck },
			{ "Scatterbug", Species::Scatterbug },
			{ "Sceptile", Species::Sceptile },
			{ "Sceptilemega", Species::Sceptile },
			{ "Scizor", Species::Scizor },
			{ "Scizormega", Species::Scizor },
			{ "Scolipede", Species::Scolipede },
			{ "Scrafty", Species::Scrafty },
			{ "Scraggy", Species::Scraggy },
			{ "Scyther", Species::Scyther },
			{ "Seadra", Species::Seadra },
			{ "Seaking", Species::Seaking },
			{ "Sealeo", Species::Sealeo },
			{ "Seedot", Species::Seedot },
			{ "Seel", Species::Seel },
			{ "Seismitoad", Species::Seismitoad },
			{ "Sentret", Species::Sentret },
			{ "Serperior", Species::Serperior },
			{ "Servine", Species::Servine },
			{ "Seviper", Species::Seviper },
			{ "Sewaddle", Species::Sewaddle },
			{ "Sharpedo", Species::Sharpedo },
			{ "Sharpedomega", Species::Sharpedo },
			{ "Shaymin", Species::Shaymin_Land },
			{ "Shayminland", Species::Shaymin_Land },
			{ "Shayminsky", Species::Shaymin_Sky },
			{ "Shedinja", Species::Shedinja },
			{ "Shelgon", Species::Shelgon },
			{ "Shellder", Species::Shellder },
			{ "Shellos", Species::Shellos },
			{ "Shelmet", Species::Shelmet },
			{ "Shieldon", Species::Shieldon },
			{ "Shiftry", Species::Shiftry },
			{ "Shiinotic", Species::Shiinotic },
			{ "Shinx", Species::Shinx },
			{ "Shroomish", Species::Shroomish },
			{ "Shuckle", Species::Shuckle },
			{ "Shuppet", Species::Shuppet },
			{ "Sigilyph", Species::Sigilyph },
			{ "Silcoon", Species::Silcoon },
			{ "Silvally", Species::Silvally },
			{ "Silvallybug", Species::Silvally },
			{ "Silvallydark", Species::Silvally },
			{ "Silvallydragon", Species::Silvally },
			{ "Silvallyelectric", Species::Silvally },
			{ "Silvallyfairy", Species::Silvally },
			{ "Silvallyfighting", Species::Silvally },
			{ "Silvallyfire", Species::Silvally },
			{ "Silvallyflying", Species::Silvally },
			{ "Silvallyghost", Species::Silvally },
			{ "Silvallygrass", Species::Silvally },
			{ "Silvallyground", Species::Silvally },
			{ "Silvallyice", Species::Silvally },
			{ "Silvallypoison", Species::Silvally },
			{ "Silvallypsychic", Species::Silvally },
			{ "Silvallyrock", Species::Silvally },
			{ "Silvallysteel", Species::Silvally },
			{ "Silvallywater", Species::Silvally },
			{ "Simipour", Species::Simipour },
			{ "Simisage", Species::Simisage },
			{ "Simisear", Species::Simisear },
			{ "Skarmory", Species::Skarmory },
			{ "Skiddo", Species::Skiddo },
			{ "Skiploom", Species::Skiploom },
			{ "Skitty", Species::Skitty },
			{ "Skorupi", Species::Skorupi },
			{ "Skrelp", Species::Skrelp },
			{ "Skuntank", Species::Skuntank },
			{ "Slaking", Species::Slaking },
			{ "Slakoth", Species::Slakoth },
			{ "Sliggoo", Species::Sliggoo },
			{ "Slowbro", Species::Slowbro },
			{ "Slowbromega", Species::Slowbro },
			{ "Slowking", Species::Slowking },
			{ "Slowpoke", Species::Slowpoke },
			{ "Slugma", Species::Slugma },
			{ "Slurpuff", Species::Slurpuff },
			{ "Smeargle", Species::Smeargle },
			{ "Smoochum", Species::Smoochum },
			{ "Sneasel", Species::Sneasel },
			{ "Snivy", Species::Snivy },
			{ "Snorlax", Species::Snorlax },
			{ "Snorunt", Species::Snorunt },
			{ "Snover", Species::Snover },
			{ "Snubbull", Species::Snubbull },
			{ "Solgaleo", Species::Solgaleo },
			{ "Solosis", Species::Solosis },
			{ "Solrock", Species::Solrock },
			{ "Spearow", Species::Spearow },
			{ "Spewpa", Species::Spewpa },
			{ "Spheal", Species::Spheal },
			{ "Spinarak", Species::Spinarak },
			{ "Spinda", Species::Spinda },
			{ "Spiritomb", Species::Spiritomb },
			{ "Spoink", Species::Spoink },
			{ "Spritzee", Species::Spritzee },
			{ "Squirtle", Species::Squirtle },
			{ "Stakataka", Species::Stakataka },
			{ "Stantler", Species::Stantler },
			{ "Staraptor", Species::Staraptor },
			{ "Staravia", Species::Staravia },
			{ "Starly", Species::Starly },
			{ "Starmie", Species::Starmie },
			{ "Staryu", Species::Staryu },
			{ "Steelix", Species::Steelix },
			{ "Steelixmega", Species::Steelix },
			{ "Steenee", Species::Steenee },
			{ "Stoutland", Species::Stoutland },
			{ "Stufful", Species::Stufful },
			{ "Stunfisk", Species::Stunfisk },
			{ "Stunky", Species::Stunky },
			{ "Sudowoodo", Species::Sudowoodo },
			{ "Suicune", Species::Suicune },
			{ "Sunflora", Species::Sunflora },
			{ "Sunkern", Species::Sunkern },
			{ "Surskit", Species::Surskit },
			{ "Swablu", Species::Swablu },
			{ "Swadloon", Species::Swadloon },
			{ "Swalot", Species::Swalot },
			{ "Swampert", Species::Swampert },
			{ "Swampertmega", Species::Swampert },
			{ "Swanna", Species::Swanna },
			{ "Swellow", Species::Swellow },
			{ "Swinub", Species::Swinub },
			{ "Swirlix", Species::Swirlix },
			{ "Swoobat", Species::Swoobat },
			{ "Sylveon", Species::Sylveon },
			{ "Taillow", Species::Taillow },
			{ "Talonflame", Species::Talonflame },
			{ "Tangela", Species::Tangela },
			{ "Tangrowth", Species::Tangrowth },
			{ "Tapubulu", Species::Tapu_Bulu },
			{ "Tapufini", Species::Tapu_Fini },
			{ "Tapukoko", Species::Tapu_Koko },
			{ "Tapulele", Species::Tapu_Lele },
			{ "Tauros", Species::Tauros },
			{ "Teddiursa", Species::Teddiursa },
			{ "Tentacool", Species::Tentacool },
			{ "Tentacruel", Species::Tentacruel },
			{ "Tepig", Species::Tepig },
			{ "Terrakion", Species::Terrakion },
			{ "Throh", Species::Throh },
			{ "Thundurus", Species::Thundurus_Incarnate },
			{ "Thundurusincarnate", Species::Thundurus_Incarnate },
			{ "Thundurustherian", Species::Thundurus_Therian },
			{ "Timburr", Species::Timburr },
			{ "Tirtouga", Species::Tirtouga },
			{ "Togedemaru", Species::Togedemaru },
			{ "Togedemarutotem", Species::Togedemaru },
			{ "Togekiss", Species::Togekiss },
			{ "Togepi", Species::Togepi },
			{ "Togetic", Species::Togetic },
			{ "Torchic", Species::Torchic },
			{ "Torkoal", Species::Torkoal },
			{ "Tornadus", Species::Tornadus_Incarnate },
			{ "Tornadusincarnate", Species::Tornadus_Incarnate },
			{ "Tornadustherian", Species::Tornadus_Therian },
			{ "Torracat", Species::Torracat },
			{ "Torterra", Species::Torterra },
			{ "Totodile", Species::Totodile },
			{ "Toucannon", Species::Toucannon },
			{ "Toxapex", Species::Toxapex },
			{ "Toxicroak", Species::Toxicroak },
			{ "Tranquill", Species::Tranquill },
			{ "Trapinch", Species::Trapinch },
			{ "Treecko", Species::Treecko },
			{ "Trevenant", Species::Trevenant },
			{ "Tropius", Species::Tropius },
			{ "Trubbish", Species::Trubbish },
			{ "Trumbeak", Species::Trumbeak },
			{ "Tsareena", Species::Tsareena },
			{ "Turtonator", Species::Turtonator },
			{ "Turtwig", Species::Turtwig },
			{ "Tympole", Species::Tympole },
			{ "Tynamo", Species::Tynamo },
			{ "Typenull", Species::Type_Null },
			{ "Typhlosion", Species::Typhlosion },
			{ "Tyranitar", Species::Tyranitar },
			{ "Tyranitarmega", Species::Tyranitar },
			{ "Tyrantrum", Species::Tyrantrum },
			{ "Tyrogue", Species::Tyrogue },
			{ "Tyrunt", Species::Tyrunt },
			{ "Umbreon", Species::Umbreon },
			{ "Unfezant", Species::Unfezant },
			{ "Unown", Species::Unown },
			{ "Ursaring", Species::Ursaring },
			{ "Uxie", Species::Uxie },
			{ "Vanillish", Species::Vanillish },
			{ "Vanillite", Species::Vanillite },
			{ "Vanilluxe", Species::Vanilluxe },
			{ "Vaporeon", Species::Vaporeon },
			{ "Venipede", Species::Venipede },
			{ "Venomoth", Species::Venomoth },
			{ "Venonat", Species::Venonat },
			{ "Venusaur", Species::Venusaur },
			{ "Venusaurmega", Species::Venusaur },
			{ "Vespiquen", Species::Vespiquen },
			{ "Vibrava", Species::Vibrava },
			{ "Victini", Species::Victini },
			{ "Victreebel", Species::Victreebel },
			{ "Vigoroth", Species::Vigoroth },
			{ "Vikavolt", Species::Vikavolt },
			{ "Vikavolttotem", Species::Vikavolt },
			{ "Vileplume", Species::Vileplume },
			{ "Virizion", Species::Virizion },
			{ "Vivillon", Species::Vivillon },
			{ "Volbeat", Species::Volbeat },
			{ "Volcanion", Species::Volcanion },
			{ "Volcarona", Species::Volcarona },
			{ "Voltorb", Species::Voltorb },
			{ "Vullaby", Species::Vullaby },
			{ "Vulpix", Species::Vulpix },
			{ "Vulpixalola", Species::Vulpix_Alolan },
			{ "Vulpixalolan", Species::Vulpix_Alolan },
			{ "Wailmer", Species::Wailmer },
			{ "Wailord", Species::Wailord },
			{ "Walrein", Species::Walrein },
			{ "Wartortle", Species::Wartortle },
			{ "Watchog", Species::Watchog },
			{ "Weavile", Species::Weavile },
			{ "Weedle", Species::Weedle },
			{ "Weepinbell", Species::Weepinbell },
			{ "Weezing", Species::Weezing },
			{ "Whimsicott", Species::Whimsicott },
			{ "Whirlipede", Species::Whirlipede },
			{ "Whiscash", Species::Whiscash },
			{ "Whismur", Species::Whismur },
			{ "Wigglytuff", Species::Wigglytuff },
			{ "Wimpod", Species::Wimpod },
			{ "Wingull", Species::Wingull },
			{ "Wishiwashi", Species::Wishiwashi_Solo },
			{ "Wishiwashischool", Species::Wishiwashi_School },
			{ "Wishiwashisolo", Species::Wishiwashi_Solo },
			{ "Wobbuffet", Species::Wobbuffet },
			{ "Woobat", Species::Woobat },
			{ "Wooper", Species::Wooper },
			{ "Wormadam", Species::Wormadam_Plant },
			{ "Wormadamplant", Species::Wormadam_Plant },
			{ "Wormadamsandy", Species::Wormadam_Sandy },
			{ "Wormadamtrash", Species::Wormadam_Trash },
			{ "Wurmple", Species::Wurmple },
			{ "Wynaut", Species::Wynaut },
			{ "Xatu", Species::Xatu },
			{ "Xerneas", Species::Xerneas },
			{ "Xurkitree", Species::Xurkitree },
			{ "Yamask", Species::Yamask },
			{ "Yanma", Species::Yanma },
			{ "Yanmega", Species::Yanmega },
			{ "Yungoos", Species::Yungoos },
			{ "Yveltal", Species::Yveltal },
			{ "Zangoose", Species::Zangoose },
			{ "Zapdos", Species::Zapdos },
			{ "Zebstrika", Species::Zebstrika },
			{ "Zekrom", Species::Zekrom },
			{ "Zeraora", Species::Zeraora },
			{ "Zigzagoon", Species::Zigzagoon },
			{ "Zoroark", Species::Zoroark },
			{ "Zorua", Species::Zorua },
			{ "Zubat", Species::Zubat },
			{ "Zweilous", Species::Zweilous },
			{ "Zygarde", Species::Zygarde_50 },
			{ "Zygarde10", Species::Zygarde_10 },
			{ "Zygarde50", Species::Zygarde_50 },
			{ "Zygardecomplete", Species::Zygarde_Complete }
	};

	return map.at(str);
}